CREATE TABLE CATEGORY (
  ID NUMBER(10, 0) NOT NULL ,
  NAME VARCHAR2(20 BYTE) ,
  STATUE VARCHAR2(2 BYTE) ,
  ORIGIN_ID NUMBER(10, 0) NOT NULL ,
  UPDATE_AT DATE DEFAULT SYSDATE,
  CONSTRAINT category_primary_key PRIMARY KEY (ID),
  CONSTRAINT CATEGORY_FK1 FOREIGN KEY
  (
    ORIGIN_ID
  )
  REFERENCES CATEGORY
  (
    ID
  )
);