CREATE SEQUENCE SUB_CATEGORY_SEQ START WITH 1;

CREATE TABLE SUB_CATEGORY (
  ID NUMBER(10, 0) NOT NULL ,
  NAME VARCHAR2(20 BYTE) ,
  STATUE VARCHAR2(2 BYTE) ,
  CATEGORY_ID NUMBER(10, 0) NOT NULL ,
  ORIGIN_ID NUMBER(10, 0) NOT NULL ,
  UPDATE_AT DATE DEFAULT SYSDATE,
  CONSTRAINT SUB_CATEGORY_PRIMARY_KEY PRIMARY KEY (ID),
  CONSTRAINT SUB_CATEGORY_FK1 FOREIGN KEY (ORIGIN_ID) REFERENCES SUB_CATEGORY (ID)
);

